version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    allow:
    - dependency-name: "*"
      dependency-type: "direct"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
    - dependency-name: "*"
      dependency-type: "direct"
  - package-ecosystem: docker-compose
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
    - dependency-name: "*"
      dependency-type: "direct"