services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=apluser
      - POSTGRES_PASSWORD=apluserpass
      - POSTGRES_DB=apldb
  ibet-hardhat-network:
    build:
      context: ./
      dockerfile: tests/Dockerfile_ibet
    ports:
      - "8545:8545"
  eth-hardhat-network:
    build:
      context: ./
      dockerfile: tests/Dockerfile_eth
    ports:
      - "8546:8545"
  ibet-prime-postgres:
    build:
      context: ./
      dockerfile: ./tests/Dockerfile_unittest
    environment:
      - TEST_DATABASE_URL=postgresql://apluser:apluserpass@postgres/apldb
      - WEB3_HTTP_PROVIDER=http://ibet:8545
      - ETH_WEB3_HTTP_PROVIDER=http://eth:8545
      - RESPONSE_VALIDATION_MODE=1
      - IBET_WET_FEATURE_ENABLED=1
      - BC_EXPLORER_ENABLED=1
      - FREEZE_LOG_FEATURE_ENABLED=1
      - DVP_AGENT_FEATURE_ENABLED=1
    links:
      - postgres:postgres
      - ibet-hardhat-network:ibet
      - eth-hardhat-network:eth
    depends_on:
      - postgres
      - ibet-hardhat-network
      - eth-hardhat-network
    volumes:
      - ./cov:/app/ibet-Prime/cov
