version: "3"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=apluser
      - POSTGRES_PASSWORD=apluserpass
      - POSTGRES_DB=apldb
  hardhat-network:
    build:
      context: ./
      dockerfile: tests/Dockerfile_hardhat
    ports:
      - "8545:8545"
  ibet-prime-postgres:
    build:
      context: ./
      dockerfile: ./tests/Dockerfile_unittest
    environment:
      - TEST_DATABASE_URL=postgresql+psycopg://apluser:apluserpass@postgres/apldb
      - WEB3_HTTP_PROVIDER=http://quorum:8545
      - RESPONSE_VALIDATION_MODE=1
    links:
      - postgres:postgres
      - hardhat-network:quorum
    depends_on:
      - postgres
      - hardhat-network
