version: "3"

services:
  postgres:
    image: postgres:10.13
    environment:
      - POSTGRES_USER=apluser
      - POSTGRES_PASSWORD=apluserpass
      - POSTGRES_DB=apldb
  ganache-cli:
    image: "trufflesuite/ganache-cli:latest"
    ports:
      - "8545:8545"
    command:
      - -g 0
  ibet-prime-postgres:
    build:
      context: ./
      dockerfile: ./tests/Dockerfile
    environment:
      - TEST_DATABASE_URL=postgresql://apluser:apluserpass@postgres/apldb
      - WEB3_HTTP_PROVIDER=http://quorum:8545
    links:
      - postgres:postgres
      - ganache-cli:quorum
    depends_on:
      - postgres
      - ganache-cli
