[tool.poetry]
name = "ibet-prime"
version = "24.9"
description = "ibet-Prime is an API service that enables the issuance and management of security tokens on the ibet network."
authors = ["BOOSTRY Co., Ltd. <dev@boostry.co.jp>"]
license = "Apache License, Version 2.0"
readme = "README.md"

[tool.poetry.scripts]
ibet-explorer = "cmd.explorer.src:main"
settlement-cli = "cmd.settlement.src:main"

[tool.poetry.dependencies]
python = "3.12.2"
alembic = "^1.13.1"
boto3 = "~1.34.59"
coincurve = "~19.0.1"
eth-keyfile = "0.8.1"
eth-utils = "~4.1.1"
fastapi = "~0.111.0"
gunicorn = "~22.0.0"
orjson = "~3.10.3"
psycopg = {extras = ["c"], version = "^3.1.18"}
pycryptodome = "~3.20"
pydantic = "~2.7.1"
pytz = "~2024.1"
shared-memory-dict = "~0.7.2"
web3 = "7.0.0b6"
httpx = "^0.27.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.28"}
uvicorn = {extras = ["standard"], version = "~0.30.0"}
uvloop = "~0.19.0"
memray = "^1.12.0"

ibet-prime-explorer = {path = "cmd/explorer", optional = true, develop = true}
ibet-prime-settlement = {path = "cmd/settlement", optional = true, develop = true}
textual = {version = "~0.44.1", optional = true}
async-cache = {version = "~1.1.1", optional = true}
typer = "0.12.3"
aiohttp = {version = "~3.9.3", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-cov = "^4.1.0"
pyyaml = "^6.0"
pre-commit = "^3.6.0"
isort = "^5.13.2"
black = "^24.1.1"
textual-dev = "^1.2.1"
pytest-alembic = "^0.10.7"
pytest-freezer = "^0.4.8"
pytest-asyncio = "0.23.3"
pytest-aiohttp = "^1.0.5"
ruamel-yaml = "^0.18.6"
pytest-memray = "^1.6.0"

[tool.poetry.extras]
ibet-explorer = [
    "ibet-prime-explorer",
    "textual",
    "async-cache",
    "typer",
    "aiohttp"
]
settlement-cli = [
    "ibet-prime-settlement",
    "typer",
]

[tool.isort]
profile = "black"
combine_as_imports = true
skip_glob = ["migrations/*"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
