[tool.poetry]
name = "ibet-prime"
version = "22.3.0"
description = "ibet-Prime is an API service that enables the issuance and management of security tokens on the ibet network."
authors = ["BOOSTRY Co., Ltd. <dev@boostry.co.jp>"]
license = "Apache License, Version 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.4"
alembic = "~1.9.4"
boto3 = "~1.26.82"
coincurve = "~18.0.0"
eth-keyfile = "0.5.1"
eth-utils = "1.10.0"
fastapi = "~0.92.0"
gunicorn = "~20.1.0"
orjson = "~3.8.7"
psycopg = {extras = ["binary"], version = "~3.1.8"}
pycryptodome = "~3.17"
pydantic = "~1.10.5"
pytz = "~2022.7.1"
requests = "~2.28.2"
shared-memory-dict = "~0.7.2"
uvicorn = "~0.20.0"
web3 = "~5.31.3"
sqlalchemy = "^2.0.4"

[tool.poetry.group.dev.dependencies]
httpx = "^0.23.3"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pyyaml = "^6.0"
pytest-freezegun = "^0.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
