[tool.poetry]
name = "ibet-prime"
version = "24.3"
description = "ibet-Prime is an API service that enables the issuance and management of security tokens on the ibet network."
authors = ["BOOSTRY Co., Ltd. <dev@boostry.co.jp>"]
license = "Apache License, Version 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.2"
alembic = "^1.13.1"
boto3 = "~1.34.59"
coincurve = "~19.0.1"
eth-keyfile = "0.7.0"
eth-utils = "~3.0.0"
fastapi = "~0.110.0"
gunicorn = "~21.2.0"
orjson = "~3.9.15"
psycopg = {extras = ["c"], version = "^3.1.18"}
pycryptodome = "~3.20"
pydantic = "~2.6.3"
pytz = "~2024.1"
shared-memory-dict = "~0.7.2"
web3 = "~6.15.1"
httpx = "^0.27.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.28"}
uvicorn = {extras = ["standard"], version = "~0.27.0"}
uvloop = "~0.19.0"

ibet-prime-explorer = {path = "cmd/explorer", optional = true, develop = true}
textual = {version = "~0.44.1", optional = true}
async-cache = {version = "~1.1.1", optional = true}
typer = {version = "~0.7.0", optional = true}
aiohttp = {version = "~3.9.3", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-cov = "^4.1.0"
pyyaml = "^6.0"
pre-commit = "^3.6.0"
isort = "^5.13.2"
httpx = "^0.27.0"
black = "^24.1.1"
textual-dev = "^1.2.1"
pytest-alembic = "^0.10.7"
pytest-freezer = "^0.4.8"
pytest-asyncio = "0.23.3"
pytest-aiohttp = "^1.0.5"

[tool.poetry.extras]
ibet-explorer = [
    "ibet-prime-explorer",
    "textual",
    "async-cache",
    "typer",
    "aiohttp"
]

[tool.isort]
profile = "black"
combine_as_imports = true
skip_glob = ["migrations/*"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
