FROM ghcr.io/foundry-rs/foundry:latest

COPY tests/run_anvil.sh /app/ibet-Prime/tests/run_anvil.sh
COPY tests/run_anvil_ibet.sh /app/ibet-Prime/tests/run_anvil_ibet.sh

WORKDIR /app/ibet-Prime

# Run anvil node
ENTRYPOINT ["bash", "/app/ibet-Prime/tests/run_anvil_ibet.sh"]