"""v0.1.0_fix/#188

Revision ID: 05eab8fbc21b
Revises: beccf439af5a
Create Date: 2021-08-02 15:04:21.851447

"""

import sqlalchemy as sa
from alembic import op

from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = "05eab8fbc21b"
down_revision = "beccf439af5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_attr_update",
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token_address", sa.String(length=42), nullable=True),
        sa.Column("updated_datetime", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema=get_db_schema(),
    )
    op.create_index(
        op.f("ix_token_attr_update_token_address"),
        "token_attr_update",
        ["token_address"],
        unique=False,
        schema=get_db_schema(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_token_attr_update_token_address"),
        table_name="token_attr_update",
        schema=get_db_schema(),
    )
    op.drop_table("token_attr_update", schema=get_db_schema())
    # ### end Alembic commands ###
