"""v0.1.0_feature/#155

Revision ID: 0d4133a5b0e3
Revises: d5d96e880adb
Create Date: 2021-06-21 20:01:39.441290

"""
import sqlalchemy as sa
from alembic import op

from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = "0d4133a5b0e3"
down_revision = "d5d96e880adb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node",
        sa.Column("endpoint_uri", sa.String(length=267), nullable=True),
        schema=get_db_schema(),
    )
    op.add_column(
        "node",
        sa.Column("priority", sa.Integer(), nullable=True),
        schema=get_db_schema(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node", "priority", schema=get_db_schema())
    op.drop_column("node", "endpoint_uri", schema=get_db_schema())
    # ### end Alembic commands ###
