"""v0.1.0_feature/#101_2

Revision ID: 0ff4f4a4e03e
Revises: 0624d4ca35a0
Create Date: 2021-05-25 19:21:05.209982

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = '0ff4f4a4e03e'
down_revision = '0624d4ca35a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledger', 'country_code', schema=get_db_schema())
    op.drop_column('ledger_details_data', 'account_address', schema=get_db_schema())
    op.alter_column('ledger_details_template', 'data_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False, schema=get_db_schema())
    op.drop_column('ledger_template', 'country_code', schema=get_db_schema())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_template', sa.Column('country_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False), schema=get_db_schema())
    op.alter_column('ledger_details_template', 'data_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True, schema=get_db_schema())
    op.add_column('ledger_details_data', sa.Column('account_address', sa.VARCHAR(length=42), autoincrement=False, nullable=True), schema=get_db_schema())
    op.add_column('ledger', sa.Column('country_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False), schema=get_db_schema())
    # ### end Alembic commands ###
