"""v23_3_0

Revision ID: 102b3b000e56
Revises: ff1d28df9f37
Create Date: 2022-12-28 14:16:11.566526

"""

import sqlalchemy as sa
from alembic import op

from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = "102b3b000e56"
down_revision = "ff1d28df9f37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_idx_e2e_messaging_type"),
        "idx_e2e_messaging",
        ["type"],
        unique=False,
        schema=get_db_schema(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_idx_e2e_messaging_type"),
        table_name="idx_e2e_messaging",
        schema=get_db_schema(),
    )
    # ### end Alembic commands ###
