"""v22_6_0_feature_216

Revision ID: 14019694164d
Revises: 6d738a5316eb
Create Date: 2022-05-09 12:51:45.305774

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = '14019694164d'
down_revision = '6d738a5316eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_account',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('investor_address', sa.String(length=42), nullable=False),
    sa.Column('keyfile', sa.JSON(), nullable=True),
    sa.Column('eoa_password', sa.String(length=2000), nullable=True),
    sa.Column('rsa_private_key', sa.String(length=8000), nullable=True),
    sa.Column('rsa_public_key', sa.String(length=2000), nullable=True),
    sa.Column('rsa_passphrase', sa.String(length=2000), nullable=True),
    sa.Column('rsa_status', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('investor_address')
    , schema=get_db_schema())
    op.create_table('investor_account_management',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('account_address', sa.String(length=42), nullable=False),
    sa.Column('investor_address', sa.String(length=42), nullable=False),
    sa.PrimaryKeyConstraint('account_address', 'investor_address')
    , schema=get_db_schema())
    op.create_table('investor_account_rsa_key_temporary',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('investor_address', sa.String(length=42), nullable=False),
    sa.Column('rsa_private_key', sa.String(length=8000), nullable=True),
    sa.Column('rsa_public_key', sa.String(length=2000), nullable=True),
    sa.Column('rsa_passphrase', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('investor_address')
    , schema=get_db_schema())
    op.alter_column('token_holder', 'hold_balance',
               existing_type=sa.BIGINT(),
               nullable=True, schema=get_db_schema())
    op.alter_column('token_holders_list', 'batch_status',
               existing_type=sa.VARCHAR(length=256),
               nullable=True, schema=get_db_schema())
    op.alter_column('token_holders_list', 'block_number',
               existing_type=sa.BIGINT(),
               nullable=True, schema=get_db_schema())
    op.alter_column('token_holders_list', 'token_address',
               existing_type=sa.VARCHAR(length=42),
               nullable=True, schema=get_db_schema())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token_holders_list', 'token_address',
               existing_type=sa.VARCHAR(length=42),
               nullable=False, schema=get_db_schema())
    op.alter_column('token_holders_list', 'block_number',
               existing_type=sa.BIGINT(),
               nullable=False, schema=get_db_schema())
    op.alter_column('token_holders_list', 'batch_status',
               existing_type=sa.VARCHAR(length=256),
               nullable=False, schema=get_db_schema())
    op.alter_column('token_holder', 'hold_balance',
               existing_type=sa.BIGINT(),
               nullable=False, schema=get_db_schema())
    op.drop_table('investor_account_rsa_key_temporary', schema=get_db_schema())
    op.drop_table('investor_account_management', schema=get_db_schema())
    op.drop_table('investor_account', schema=get_db_schema())
    # ### end Alembic commands ###
