"""v22_12_0_feature_401

Revision ID: 1dddc4e2d4e6
Revises: 5b1e810b1e89
Create Date: 2022-10-12 23:12:33.296953

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = '1dddc4e2d4e6'
down_revision = '5b1e810b1e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_cache',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('token_address', sa.String(length=42), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('cached_datetime', sa.DateTime(), nullable=True),
    sa.Column('expiration_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token_address')
    , schema=get_db_schema())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_cache', schema=get_db_schema())
    # ### end Alembic commands ###
