"""v21.12.0_feature/#230

Revision ID: 1f7cfdc93391
Revises: 8bde2ff68ed1
Create Date: 2021-12-09 15:48:03.701366

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = '1f7cfdc93391'
down_revision = '8bde2ff68ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_token_info',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_address', sa.String(length=42), nullable=True),
    sa.Column('is_manual_transfer_approval', sa.Boolean(), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    , schema=get_db_schema())
    op.create_index(op.f('ix_additional_token_info_token_address'), 'additional_token_info', ['token_address'], unique=False, schema=get_db_schema())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_additional_token_info_token_address'), table_name='additional_token_info', schema=get_db_schema())
    op.drop_table('additional_token_info', schema=get_db_schema())
    # ### end Alembic commands ###
