"""v21.12.0_feature/#227

Revision ID: 23aeb0e53694
Revises: 9c694b5e95aa
Create Date: 2021-12-08 11:16:42.327935

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = '23aeb0e53694'
down_revision = '9c694b5e95aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idx_transfer_approval', sa.Column('exchange_address', sa.String(length=42), nullable=True), schema=get_db_schema())
    op.create_index(op.f('ix_idx_transfer_approval_exchange_address'), 'idx_transfer_approval', ['exchange_address'], unique=False, schema=get_db_schema())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idx_transfer_approval_exchange_address'), table_name='idx_transfer_approval', schema=get_db_schema())
    op.drop_column('idx_transfer_approval', 'exchange_address', schema=get_db_schema())
    # ### end Alembic commands ###
