"""v23.3.0_feature_465

Revision ID: 3a0cc5e324b4
Revises: 6920ad60f134
Create Date: 2023-01-17 18:15:07.271586

"""
import sqlalchemy as sa
from alembic import op

from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = "3a0cc5e324b4"
down_revision = "6920ad60f134"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "idx_transfer",
        sa.Column("data", sa.JSON(), nullable=True),
        schema=get_db_schema(),
    )
    # ### end Alembic commands ###

    # NOTE: Manually modified
    #   1. Added server_default arg to migrate existing record.
    #   2. Added alter column operation to remove server default setting.
    op.add_column(
        "idx_transfer",
        sa.Column(
            "source_event",
            sa.String(length=50),
            server_default="Transfer",
            nullable=False,
        ),
        schema=get_db_schema(),
    )
    op.alter_column(
        "idx_transfer",
        "source_event",
        existing_type=sa.String(length=50),
        existing_nullable=False,
        server_default=None,
        schema=get_db_schema(),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("idx_transfer", "data", schema=get_db_schema())
    op.drop_column("idx_transfer", "source_event", schema=get_db_schema())
    # ### end Alembic commands ###
