"""v22_9_0_feature_354

Revision ID: 47bf57b85b0a
Revises: 38eb462293cd
Create Date: 2022-07-15 16:34:04.214970

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = '47bf57b85b0a'
down_revision = '38eb462293cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('issuer_address', sa.String(length=42), nullable=False),
    sa.Column('auth_token', sa.String(length=64), nullable=True),
    sa.Column('usage_start', sa.DateTime(), nullable=True),
    sa.Column('valid_duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('issuer_address')
    , schema=get_db_schema())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_token', schema=get_db_schema())
    # ### end Alembic commands ###
