"""v0.1.0_feature_114

Revision ID: 498c64b0a5ad
Revises: ff1cb5a4411c
Create Date: 2021-05-24 20:02:56.156876

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = '498c64b0a5ad'
down_revision = 'ff1cb5a4411c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_events', sa.Column('event_id', sa.String(length=36), nullable=True), schema=get_db_schema())
    op.create_index(op.f('ix_scheduled_events_event_id'), 'scheduled_events', ['event_id'], unique=False, schema=get_db_schema())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_events_event_id'), table_name='scheduled_events', schema=get_db_schema())
    op.drop_column('scheduled_events', 'event_id', schema=get_db_schema())
    # ### end Alembic commands ###
