"""v23.3.0_feature_471

Revision ID: 7d09371c365e
Revises: 3a0cc5e324b4
Create Date: 2023-01-31 15:08:30.238839

"""
import sqlalchemy as sa
from alembic import op

from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = "7d09371c365e"
down_revision = "3a0cc5e324b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    # NOTE: Manually modified
    #   1. Added server_default arg to migrate existing record.
    #   2. Added alter column operation to remove server default setting.
    op.add_column(
        "token_holder",
        sa.Column("locked_balance", sa.BigInteger(), server_default="0", nullable=True),
        schema=get_db_schema(),
    )
    op.alter_column(
        "token_holder",
        "locked_balance",
        existing_type=sa.BigInteger(),
        existing_nullable=True,
        server_default=None,
        schema=get_db_schema(),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token_holder", "locked_balance", schema=get_db_schema())
    # ### end Alembic commands ###
