"""v0.1.0_feature/#118

Revision ID: 8bc12b649779
Revises: b54c7dbe300d
Create Date: 2021-06-01 13:50:21.843610

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = '8bc12b649779'
down_revision = 'b54c7dbe300d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.String(length=36), nullable=True),
    sa.Column('issuer_address', sa.String(length=42), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('metainfo', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    , schema=get_db_schema())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification', schema=get_db_schema())
    # ### end Alembic commands ###
