"""v21.12.0_feature/#230_2

Revision ID: b1f9da1daeb3
Revises: 9a178cb445c2
Create Date: 2021-12-21 13:31:16.534558

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = 'b1f9da1daeb3'
down_revision = '9a178cb445c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idx_transfer_approval', sa.Column('transfer_approved', sa.Boolean(), nullable=True), schema=get_db_schema())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idx_transfer_approval', 'transfer_approved', schema=get_db_schema())
    # ### end Alembic commands ###
