"""v22.9.0.feature_354

Revision ID: e377b9202f25
Revises: 38eb462293cd
Create Date: 2022-07-15 17:44:44.428180

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = 'e377b9202f25'
down_revision = '38eb462293cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_access_token',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('issuer_address', sa.String(length=42), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('expiration_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name', 'issuer_address')
    , schema=get_db_schema())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary_access_token', schema=get_db_schema())
    # ### end Alembic commands ###
