"""v23.6.0_feature_511

Revision ID: e9fd0103280b
Revises: a1e5a5a6745e
Create Date: 2023-04-18 23:44:11.119965

"""
import sqlalchemy as sa
from alembic import op

from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = "e9fd0103280b"
down_revision = "a1e5a5a6745e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_force_unlock",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=True),
        sa.Column("token_address", sa.String(length=42), nullable=False),
        sa.Column("token_type", sa.String(length=40), nullable=False),
        sa.Column("account_address", sa.String(length=42), nullable=False),
        sa.Column("lock_address", sa.String(length=42), nullable=False),
        sa.Column("recipient_address", sa.String(length=42), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=get_db_schema(),
    )
    op.create_index(
        op.f("ix_batch_force_unlock_batch_id"),
        "batch_force_unlock",
        ["batch_id"],
        unique=False,
        schema=get_db_schema(),
    )
    op.create_index(
        op.f("ix_batch_force_unlock_status"),
        "batch_force_unlock",
        ["status"],
        unique=False,
        schema=get_db_schema(),
    )
    op.create_table(
        "batch_force_unlock_upload",
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("issuer_address", sa.String(length=42), nullable=False),
        sa.Column("token_address", sa.String(length=42), nullable=False),
        sa.Column("token_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("batch_id"),
        schema=get_db_schema(),
    )
    op.create_index(
        op.f("ix_batch_force_unlock_upload_issuer_address"),
        "batch_force_unlock_upload",
        ["issuer_address"],
        unique=False,
        schema=get_db_schema(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_batch_force_unlock_upload_issuer_address"),
        table_name="batch_force_unlock_upload",
        schema=get_db_schema(),
    )
    op.drop_table("batch_force_unlock_upload", schema=get_db_schema())
    op.drop_index(
        op.f("ix_batch_force_unlock_status"),
        table_name="batch_force_unlock",
        schema=get_db_schema(),
    )
    op.drop_index(
        op.f("ix_batch_force_unlock_batch_id"),
        table_name="batch_force_unlock",
        schema=get_db_schema(),
    )
    op.drop_table("batch_force_unlock", schema=get_db_schema())
    # ### end Alembic commands ###
