"""v23.6.0_feature_510

Revision ID: fedec7fb783a
Revises: 90b5d4040e8f
Create Date: 2023-05-01 19:49:40.649457

"""

import sqlalchemy as sa
from alembic import op

from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = "fedec7fb783a"
down_revision = "90b5d4040e8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "update_token",
        sa.Column("original_contents", sa.JSON(), nullable=True),
        schema=get_db_schema(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("update_token", "original_contents", schema=get_db_schema())
    # ### end Alembic commands ###
