"""
Copyright BOOSTRY Co., Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.

You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
"""

from collections.abc import Iterator, MutableMapping
from multiprocessing.shared_memory import SharedMemory
from typing import Any, ItemsView, KeysView, ValuesView

class SharedMemoryDict(MutableMapping[str, Any]):
    _memory_block: SharedMemory

    def __init__(self, name: str, size: int, *, serializer: Any = ...) -> None: ...
    def clear(self) -> None: ...
    def cleanup(self) -> None: ...
    def _save_memory(self, db: dict[str, Any]) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def keys(self) -> KeysView[str]: ...
    def values(self) -> ValuesView[Any]: ...
    def items(self) -> ItemsView[str, Any]: ...
    def pop(self, key: str, default: Any = ...) -> Any: ...
