name: Auto Assign
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@f4648c0a9fdb753479e9e75fc251f507ce17bb7e  # v2.0.0