name: Build Container

on:
  push:
    tags:
      - v*

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build and Push (ibet-prime)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          no-cache: true
          push: true
          tags: ghcr.io/boostryjp/ibet-prime:${{ steps.get_tag_name.outputs.VERSION }}
