name: Unit Test
on: [pull_request]

jobs:
  build:
    name: 'Build docker image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-test-image
  lint-ruff:
    name: 'Lint check (ruff)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  unit-test-postgres:
    name: 'Unit tests (PostgreSQL)'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: write
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - uses: actions/checkout@v4
      - name: Change owner of output directory
        run: |
          sudo chown -R runner:docker /home/runner/work/ibet-Prime/ibet-Prime/cov
          sudo chmod 777 /home/runner/work/ibet-Prime/ibet-Prime/cov
      - uses: ./.github/actions/setup-test-image
      - name: run unit test using postgres
        run: docker compose run ibet-prime-postgres
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: cov/coverage.xml
          junitxml-path: cov/pytest.xml
          report-only-changed-files: true
  migration-test-postgres:
    name: 'Migration tests (PostgreSQL)'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-test-image
      - name: run unit test using postgres
        run: docker compose run ibet-prime-postgres bash --login -c "cd /app/ibet-Prime && pytest -vv --test-alembic -m 'alembic'"
